### PR TITLE
Migrate to ViewPager2

### PR DESCRIPTION
**Pull request by TacoTheDank**
### 1st commit
- Update gradle wrapper to 6.7.1 using git bash

### 2nd commit
- Update minimum CMake 3.4.1 -> 3.10.2
- Update Android Studio 4.0.1 -> 4.1.1
- Clean up build.gradle files

### 3rd commit
- Migrate to ViewPager2

Tested and worked fine.

### CODE REVIEW

**Comment by kasnder** [comment]
Amazing! Thanks for the PR. Code looks good, but I’ll check on a few devices first before merging.

**Comment by TacoTheDank** [comment]
@kasnder I tested an APK on my own Android 10 device, and all three tabs worked fine. I don't know about below Nougat though.

**Comment by TacoTheDank** [comment]
@kasnder Any updates? :)

**Comment by chris-tian78** [comment]
@kasnder I can confirm that the changes work without any problems. I have created a test version.
https://github.com/chris-tian78/tracker-control-android

**Comment by kasnder** [comment]
I’ve checked this now and will merge this soon. Sorry for the delay. It’s quite busy on my end. I still need to check compatibility with F-Droid.

**Comment by kasnder** [comment]
Merged this now. Many thanks for your support and hope you understand!

**Comment by TacoTheDank** [comment]
@kasnder Thanks! :)

**Pull request merged**
